# Generated by Django 4.0.4 on 2022-05-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('SFHT', 'Startup Finance & High Technologies'), ('IBHT', 'Innovative Banking & High Technologies'), ('DHT', 'Design & High Technologies'), ('SEST', 'Software Engineering & Social Transformations'), ('ECOL', 'Ecology & Energy Efficiency'), ('DMDT', 'Design management & Digital Technologies'), ('EHI', 'Engineering & Humanities probably?'), ('MIX', 'Mix')], max_length=256)),
                ('starting_year', models.IntegerField()),
                ('group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('is_superuser', models.IntegerField()),
                ('first_name', models.CharField(default='', max_length=1024)),
                ('second_name', models.CharField(default='', max_length=1024)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='new.course')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math', 'Математика'), ('Phys', 'Физика'), ('Chem', 'Химия'), ('Info', 'Информатика'), ('Engl', 'Английский язык')], max_length=256)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='new.user')),
                ('tuties', models.ManyToManyField(related_name='tuties', to='new.user')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=32)),
                ('club_description', models.CharField(max_length=1024)),
                ('club_logo', models.ImageField(upload_to='club_logos')),
                ('club_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_leader', to='new.user')),
                ('participants', models.ManyToManyField(related_name='clubs_participants', to='new.user')),
            ],
        ),
    ]
