# Generated by Django 4.0.4 on 2022-05-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
                ('is_superuser', models.IntegerField()),
                ('is_tutor', models.IntegerField()),
                ('first_name', models.CharField(max_length=1024)),
                ('second_name', models.CharField(max_length=1024)),
                ('clubs', models.ManyToManyField(to='new.club')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new.course')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='new.user')),
            ],
        ),
    ]
