# Generated by Django 4.0.4 on 2022-05-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=models.CharField(choices=[('Математика', 'Math'), ('Физика', 'Phys'), ('Химия', 'Chem'), ('Информатика', 'Info'), ('Английский язык', 'Engl')], max_length=256),
        ),
    ]
